export const ROUTES = {
  HOME: '/',
  TEMPLATES: '/templates',
  PRICING: '/pricing',
  HOW_IT_WORKS: '/how-it-works',
  TRY: '/try',
  CHECKOUT: '/checkout',
  PAYMENT_STATUS: '/payment/:token',
  paymentStatus: (token) => `/payment/${token}`,
  ABOUT: '/about',
  CONTACT: '/contact',
  FAQ: '/faq',
  TERMS: '/terms',
  PRIVACY: '/privacy',

  LOGIN: '/login',
  REGISTER: '/register',
  FORGOT_PASSWORD: '/forgot-password',
  RESET_PASSWORD: '/reset-password/:token',
  resetPassword: (token) => `/reset-password/${token}`,

  DASHBOARD: '/dashboard',
  DASHBOARD_EVENTS: '/dashboard/events',
  DASHBOARD_CREATE_EVENT: '/dashboard/events/new',
  DASHBOARD_EVENT_DETAIL: '/dashboard/events/:id',
  eventDetail: (id) => `/dashboard/events/${id}`,
  DASHBOARD_EVENT_SETTINGS: '/dashboard/events/:id/settings',
  eventSettings: (id) => `/dashboard/events/${id}/settings`,
  DASHBOARD_EVENT_BUILDER: '/dashboard/events/:id/builder',
  eventBuilder: (id) => `/dashboard/events/${id}/builder`,
  DASHBOARD_EVENT_GUESTS: '/dashboard/events/:id/guests',
  eventGuests: (id) => `/dashboard/events/${id}/guests`,
  DASHBOARD_EVENT_ANALYTICS: '/dashboard/events/:id/analytics',
  eventAnalytics: (id) => `/dashboard/events/${id}/analytics`,

  INVITE: '/invite/:slug',
  invite: (slug) => `/invite/${slug}`,
  CARD: '/card/:token',
  card: (token) => `/card/${token}`,
  DASHBOARD_NOTIFICATIONS: '/dashboard/notifications',
  DASHBOARD_BILLING: '/dashboard/billing',
  DASHBOARD_ORDERS: '/dashboard/orders',
  DASHBOARD_ORDER_DETAIL: '/dashboard/orders/:id',
  orderDetail: (id) => `/dashboard/orders/${id}`,
  DASHBOARD_SETTINGS: '/dashboard/settings',
  DASHBOARD_SETTINGS_PROFILE: '/dashboard/settings/profile',
  DASHBOARD_SETTINGS_SECURITY: '/dashboard/settings/security',
  DASHBOARD_SETTINGS_NOTIFICATIONS: '/dashboard/settings/notifications',
  DASHBOARD_SETTINGS_LANGUAGE: '/dashboard/settings/language',

  ADMIN: '/admin',
  ADMIN_CUSTOMERS: '/admin/customers',
  ADMIN_CUSTOMER_DETAIL: '/admin/customers/:id',
  adminCustomerDetail: (id) => `/admin/customers/${id}`,
  ADMIN_EVENTS: '/admin/events',
  ADMIN_TEMPLATES: '/admin/templates',
  ADMIN_ORDERS: '/admin/orders',
  ADMIN_ORDER_DETAIL: '/admin/orders/:id',
  adminOrderDetail: (id) => `/admin/orders/${id}`,
  ADMIN_AUDIT_LOGS: '/admin/audit-logs',

  NOT_FOUND: '*',
};
